# Generated by Django 3.0.5 on 2024-03-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_feedback_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('created_date', models.DateField(null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=40)),
                ('date_modified', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.CharField(choices=[('Paper', 'Paper'), ('Board & kraft machines', 'Board & kraft machines'), ('Drying cylinders', 'Drying cylinders'), ('Press rolls and Suction rolls', 'Press rolls and Suction rolls')], max_length=50, null=True),
        ),
    ]
