# Generated by Django 3.0.5 on 2024-03-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sname',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
