# Generated by Django 3.0.5 on 2024-03-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_product_sname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sname',
            new_name='user_id',
        ),
    ]
