# Generated by Django 3.0.5 on 2024-03-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_auto_20240319_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='description',
        ),
    ]
